# -*- coding: utf-8 -*-
"""AI_LAB_ASSIGNMENT2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OCQb4FIoUrLCRXj8uJ8eSrVCQOEZb6FA

Amna Iftikhar (SP23-BCS-071)
"""

!ls /content/drive/

!ls /content/drive/MyDrive/AI/"archive (3)"/nsl-kdd

column_names = [
    'duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes',
    'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins',
    'logged_in', 'num_compromised', 'root_shell', 'su_attempted',
    'num_root', 'num_file_creations', 'num_shells', 'num_access_files',
    'num_outbound_cmds', 'is_host_login', 'is_guest_login', 'count',
    'srv_count', 'serror_rate', 'srv_serror_rate', 'rerror_rate',
    'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate', 'srv_diff_host_rate',
    'dst_host_count', 'dst_host_srv_count', 'dst_host_same_srv_rate',
    'dst_host_diff_srv_rate', 'dst_host_same_src_port_rate',
    'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
    'dst_host_srv_serror_rate', 'dst_host_rerror_rate',
    'dst_host_srv_rerror_rate', 'label', 'difficulty'
]

import pandas as pd

train_path = "/content/drive/MyDrive/AI/archive (3)/nsl-kdd/KDDTrain+.txt"
test_path  = "/content/drive/MyDrive/AI/archive (3)/nsl-kdd/KDDTest+.txt"

train = pd.read_csv(train_path, names=column_names)
test = pd.read_csv(test_path, names=column_names)

train.head()

train['label'] = train['label'].apply(lambda x: 0 if x == 'normal' else 1)
test['label'] = test['label'].apply(lambda x: 0 if x == 'normal' else 1)

cat_cols = ["protocol_type", "service", "flag"]

train = pd.get_dummies(train, columns=cat_cols)
test = pd.get_dummies(test, columns=cat_cols)

train, test = train.align(test, join='left', axis=1, fill_value=0)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(train.drop("label", axis=1))
X_test  = scaler.transform(test.drop("label", axis=1))

y_train = train["label"]
y_test  = test["label"]

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score

rf = RandomForestClassifier(n_estimators=100)
rf.fit(X_train, y_train)

rf_pred = rf.predict(X_test)

print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))
print(classification_report(y_test, rf_pred))

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

model = Sequential([
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dropout(0.3),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(X_train, y_train, epochs=10, batch_size=64, validation_split=0.2)

dnn_pred = (model.predict(X_test) > 0.5).astype("int32")

print("DNN Accuracy:", accuracy_score(y_test, dnn_pred))
print(classification_report(y_test, dnn_pred))

import numpy as np

hybrid_pred = np.round((rf_pred + dnn_pred.flatten()) / 2)
rf_prob = rf.predict_proba(X_test)[:,1]
dnn_prob = model.predict(X_test).flatten()

hybrid_prob = (rf_prob + dnn_prob) / 2
hybrid_pred = (hybrid_prob > 0.5).astype(int)
print("Hybrid Model Accuracy:", accuracy_score(y_test, hybrid_pred))
print(classification_report(y_test, hybrid_pred))

import pandas as pd

results = pd.DataFrame({
    "Model": ["RandomForest", "DNN", "Hybrid"],
    "Accuracy": [
        accuracy_score(y_test, rf_pred),
        accuracy_score(y_test, dnn_pred),
        accuracy_score(y_test, hybrid_pred)
    ]
})

results

import matplotlib.pyplot as plt

plt.figure(figsize=(6,4))
plt.bar(results["Model"], results["Accuracy"])
plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")
plt.savefig("/content/accuracy.png")
plt.show()

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title("DNN Accuracy Curve")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend(["Train", "Validation"])
plt.show()

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title("DNN Accuracy Curve")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend(["Train", "Validation"])
plt.savefig("/content/accuracy2.png")
plt.show()