# -*- coding: utf-8 -*-
"""lab2task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hdIhO7c-ZddglRSWRx6Ae9omY152fnN_
"""



"""1.   Matplotlib

2.  Numpy

3.   List
"""

num=[1,2,3,45,6,7,8,9,10]
print(num)

num=[1,2,3,45,6,7,8,9,10]

print('sum:', sum(num))

num=[1,2,3,45,6,7,8,9,10]
print('MIN:', min(num))

num=[1,2,3,45,6,7,8,9,10]
print('MAX:', max(num))

num=[1,2,3,45,6,7,8,9,10]
num.append(66)
num.remove(1)
print('UPDATED LIST: ', num)

num=[1,2,3,45,6,7,8,9,10]
print('ASCENDING: ', sorted(num))
print('DESCENDING: ', sorted(num, reverse=True))

"""

4.   Tuple

"""

name= ('ali', 'ahmed', 'sana', 'zara', 'soha')
print(name)

print("Second element: ", name[1])
print("Last element: ", name[-1])

name= ('ali', 'ahmed', 'sana', 'zara', 'soha')
name[1]='akhi'

name= ('ali', 'ahmed', 'sana', 'zara', 'soha')
name_list= list(name)
name_list[1]= 'akhi'
print('Modified List: ', name_list)

"""

5.   Set

"""

name1={'ali', 'ahmed', 'zara'}
name2={'ali', 'ahmed', 'zara','ali', 'zain', 'zoha'}

print('UNION: ', name1.union(name2))
print('Intersaction:', name1.intersection(name2))
print('Difference: ', name2.difference(name1))

name1={'ali', 'ahmed', 'zara'}
name2={'ali', 'ahmed', 'zara','ali', 'zain', 'zoha'}

name1.add('zain')
name2.remove('ali')
print('MODIFIED SET 1:', name1)
print('MODIFIED SET 2:', name2)

"""

6.   Dictionary

"""

student_marks = {
    " ali": 85,
    "behram": 92,
    "hala": 78,
    "zoha": 90,
    "zara": 88
}

print('KEYS: ', student_marks.keys())
print('VALUES: ', student_marks.values())

student_marks = {
    " ali": 85,
    "behram": 92,
    "hala": 78,
    "zoha": 90,
    "zara": 88
}

student_marks['hala']= 44
print('MODIFIED DICTIONARY: ', student_marks)

student_marks = {
    "ali": 85,
    "ali": 92,
    "ali": 78,
    "ali": 90,
    "ali": 88
}

print(student_marks)