# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10yb6mG3pzHZz7Zd-PG7AD2uM3XTWaPtb
"""

import numpy as np

# -------------------------------
# 0) Change input values here
# -------------------------------
x1 = 0.2
x2 = 0.7

# Initial weights (same as original)
w1, w2 = 0.15, 0.20
w3, w4 = 0.25, 0.30
w5, w6 = 0.40, 0.45
w7, w8 = 0.50, 0.55

b1 = 0.35
b2 = 0.60

T1 = 0.01
T2 = 0.99

lr = 0.5


# -------------------------------
# 1) Activations
# -------------------------------
def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-z))

def sigmoid_derivative(a):
    return a * (1 - a)

def softmax(z):
    e = np.exp(z - np.max(z))   # stable softmax
    return e / np.sum(e)


# -------------------------------
# 2) Forward pass
# -------------------------------
def forward_pass(x1, x2, w1, w2, w3, w4, w5, w6, w7, w8, b1, b2):
    # Hidden layer
    H1_net = x1 * w1 + x2 * w2 + b1
    H2_net = x1 * w3 + x2 * w4 + b1

    H1 = sigmoid(H1_net)
    H2 = sigmoid(H2_net)

    # Output layer nets
    y1_net = H1 * w5 + H2 * w6 + b2
    y2_net = H1 * w7 + H2 * w8 + b2

    # ------- SOFTMAX ACTIVATION -------
    y1, y2 = softmax(np.array([y1_net, y2_net]))

    return {
        "H1": H1, "H2": H2,
        "H1_net": H1_net, "H2_net": H2_net,
        "y1_net": y1_net, "y2_net": y2_net,
        "y1": y1, "y2": y2
    }


# -------------------------------
# 3) Forward (before update)
# -------------------------------
print("\n=== FORWARD (before update) ===")
out = forward_pass(x1, x2, w1, w2, w3, w4, w5, w6, w7, w8, b1, b2)
y1, y2 = out["y1"], out["y2"]

print(f"y1 = {y1:.9f}")
print(f"y2 = {y2:.9f}")

E1 = 0.5 * (T1 - y1)**2
E2 = 0.5 * (T2 - y2)**2
E_total = E1 + E2

print(f"Total error = {E_total:.9f}")


# -------------------------------
# 4) Backprop: Output layer (softmax + SSE)
# -------------------------------
# dE/dz_i = (y_i - T_i)
delta1 = (y1 - T1)
delta2 = (y2 - T2)

dw5 = delta1 * out["H1"]
dw6 = delta1 * out["H2"]
dw7 = delta2 * out["H1"]
dw8 = delta2 * out["H2"]

# Update output weights
w5_new = w5 - lr * dw5
w6_new = w6 - lr * dw6
w7_new = w7 - lr * dw7
w8_new = w8 - lr * dw8


# -------------------------------
# 5) Backprop: Hidden layer
# -------------------------------
# Hidden deltas use original weights
delta_H1 = (delta1 * w5 + delta2 * w7) * sigmoid_derivative(out["H1"])
delta_H2 = (delta1 * w6 + delta2 * w8) * sigmoid_derivative(out["H2"])

dw1 = delta_H1 * x1
dw2 = delta_H1 * x2
dw3 = delta_H2 * x1
dw4 = delta_H2 * x2

w1_new = w1 - lr * dw1
w2_new = w2 - lr * dw2
w3_new = w3 - lr * dw3
w4_new = w4 - lr * dw4

# Update biases
b2_new = b2 - lr * (delta1 + delta2)
b1_new = b1 - lr * (delta_H1 + delta_H2)


# -------------------------------
# 6) Forward pass after update
# -------------------------------
out_after = forward_pass(
    x1, x2,
    w1_new, w2_new, w3_new, w4_new,
    w5_new, w6_new, w7_new, w8_new,
    b1_new, b2_new
)

y1_after, y2_after = out_after["y1"], out_after["y2"]
E_after = 0.5*(T1 - y1_after)**2 + 0.5*(T2 - y2_after)**2

print("\n=== AFTER UPDATE ===")
print(f"y1 = {y1_after:.9f}")
print(f"y2 = {y2_after:.9f}")
print(f"E_total (before) = {E_total:.9f}")
print(f"E_total (after)  = {E_after:.9f}")